# Generated by Django 3.1.3 on 2022-04-13 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('idUser', models.IntegerField(max_length=256, primary_key=True, serialize=False)),
                ('idWallet', models.CharField(max_length=42)),
                ('coinInGame', models.DecimalField(decimal_places=6, max_digits=10)),
            ],
        ),
    ]
