# Generated by Django 3.1.3 on 2022-04-13 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='idUser',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
